version: "3.9"

services:
  postgres-seed:
    build:
      context: ..
      dockerfile: postgres-seed/Dockerfile
    hostname: postgres-seed
    container_name: postgres-seed
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/home/app/src
      - /home/patrik/repos/pysystemtrade/data/futures:/path/in/container:rw

  db_postgres:
    image: postgres:15.3
    hostname: db_postgres
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./src/scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
      - /home/patrik/repos/pysystemtrade/data/futures:/path/in/container
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

volumes:
  db-postgres:
    driver: local

